package tray

import _ "embed"

// Icon assets are generated by tray/gen; regenerate with: go run ./tray/gen

//go:embed icons/disconnected.ico
var iconDisconnected []byte

//go:embed icons/connecting.ico
var iconConnecting []byte

//go:embed icons/connected.ico
var iconConnected []byte

//go:embed icons/error.ico
var iconError []byte

//go:embed icons/fallback.ico
var iconFallback []byte
